# Generated by Django 5.2.4 on 2025-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('inquiry_type', models.CharField(choices=[('website', 'Webサイト制作'), ('maintenance', '保守・更新'), ('consulting', '相談・見積もり'), ('other', 'その他')], default='other', max_length=50, verbose_name='ご相談内容の種類')),
                ('contact_method', models.CharField(choices=[('email', 'メール'), ('phone', '電話'), ('either', 'どちらでも可')], default='email', max_length=20, verbose_name='ご希望の連絡方法')),
                ('message', models.TextField(verbose_name='お問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='お問い合わせ日時')),
                ('replied', models.BooleanField(default=False, verbose_name='返信済み')),
                ('reply_message', models.TextField(blank=True, null=True, verbose_name='返信内容')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='返信日時')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
                'ordering': ['-created_at'],
            },
        ),
    ]
