"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9$0^2cr00bw+(v%5gmkjq5st^()(r^t4f(+(-c2fko&$7g3x50'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['160.251.181.156', 'praxisweb.jp', 'www.praxisweb.jp']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contact'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# config/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'contact_db',  # 使用するデータベース名
        'USER': 'retsushi',    # MySQLのユーザー名
        'PASSWORD': 'Retsushi.0718', # MySQLのパスワード
        'HOST': 'localhost',          # MySQLが動作しているホスト (通常はlocalhost)
        'PORT': '3306',               # MySQLのポート (デフォルトは3306)
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # 静的ファイルのディレクトリ
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #本番環境静的ファイル

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# config/settings.py (末尾のEMAIL_BACKEND設定の下あたりに追加)

# メールアドレス設定
ADMIN_EMAIL = 'marktwo0913@icloud.com' # 管理者（通知を受け取りたい）のメールアドレス
DEFAULT_FROM_EMAIL = 'praxisweb365@gmail.com' # 送信元のメールアドレス (例: info@your-company.com など)
SERVER_EMAIL = DEFAULT_FROM_EMAIL # サーバーからのエラーメールなどの送信元

# config/settings.py (ファイルの末尾付近)

# --- メール設定 (Gmail SMTPの例) ---
# 開発中のコンソール出力から、実際のSMTP送信に変更
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # Gmailの場合
EMAIL_PORT = 587             # GmailのTLSポート
EMAIL_USE_TLS = True         # TLS暗号化を使用
EMAIL_HOST_USER = 'praxisweb365@gmail.com' # ★あなたのGmailアドレス
EMAIL_HOST_PASSWORD = 'ztqc tesq frlb nwzk' # ★Gmailのアプリパスワード

# デフォルトの送信元メールアドレス
DEFAULT_FROM_EMAIL = 'praxisweb365@gmail.com' # あなたのGmailアドレスまたは、ドメインメールアドレス
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# 管理者への通知メールアドレス
ADMIN_EMAIL = 'marktwo0913@icloud.com' # 通知を受け取りたいメールアドレス

# --- 注意 ---
# EMAIL_HOST_PASSWORD は直接コードに書かずに、環境変数などを使うのがより安全ですが、
# 開発の初期段階ではこの方法でも問題ありません。
# 本番運用時は環境変数化を強く推奨します。